// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_weather_time.h"
#include "screens/ui_startup_page.h"
#include "screens/ui_functions_loading_page_1.h"
#include "screens/ui_functions_loading_page_2.h"
#include "screens/ui_functions_loading_page_3.h"
#include "screens/ui_functions_loading_page_4.h"
#include "screens/ui_functions_loading_page_5.h"
#include "screens/ui_functions_loading_page_6.h"
#include "screens/ui_Gallery_pictures.h"
#include "screens/ui_joks.h"
#include "screens/ui_activity_game.h"
#include "screens/ui_function_5.h"
#include "screens/ui_function_6.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * sec_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * min_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * hour_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * left_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * right_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * opa_on_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * dots_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * top_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * cloud_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * blood2_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * blood1_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * heart_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bg3_png);   // assets/bg3.png
LV_IMG_DECLARE( ui_img_rain_png);   // assets/rain.png
LV_IMG_DECLARE( ui_img_wind_png);   // assets/wind.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets/sun.png
LV_IMG_DECLARE( ui_img_clouds_png);   // assets/clouds.png
LV_IMG_DECLARE( ui_img_flash_png);   // assets/flash.png
LV_IMG_DECLARE( ui_img_536642854);   // assets/Screenshot 2026-04-13 at 11.06.53.png
LV_IMG_DECLARE( ui_img_1257899884);   // assets/Screenshot 2026-04-13 at 22.48.24.png
LV_IMG_DECLARE( ui_img_bg1_png);   // assets/bg1.png
LV_IMG_DECLARE( ui_img_btn_bg_1_png);   // assets/btn_bg_1.png
LV_IMG_DECLARE( ui_img_btn_bg_3_png);   // assets/btn_bg_3.png
LV_IMG_DECLARE( ui_img_call1_png);   // assets/call1.png

// FONTS
LV_FONT_DECLARE( ui_font_H1);
LV_FONT_DECLARE( ui_font_Number_big);
LV_FONT_DECLARE( ui_font_Number_extra);
LV_FONT_DECLARE( ui_font_Subtitle);
LV_FONT_DECLARE( ui_font_Title);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
