[env:esp32-s3-16mb]
platform = espressif32
board = esp32s3box
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv


build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I include/
    -I lib/ui/
    -I .pio/libdeps/esp32-s3-16mb/lvgl/src

lib_ldf_mode = deep

lib_deps =
    lvgl/lvgl@^9.2.2
    https://github.com/lewisxhe/SensorLib.git
    bblanchon/ArduinoJson@^7.0.3
    tzapu/WiFiManager
    bitbank2/JPEGDEC


