// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_ACTIVITY_GAME_H
#define UI_ACTIVITY_GAME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_activity_game
extern void ui_activity_game_screen_init(void);
extern void ui_activity_game_screen_destroy(void);
extern lv_obj_t *ui_activity_game;
extern lv_obj_t *ui_bg_10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

