// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_function_6 = NULL;lv_obj_t *ui_bg_12 = NULL;
// event funtions

// build funtions

void ui_function_6_screen_init(void)
{
ui_function_6 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_function_6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_function_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_function_6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg_12 = lv_image_create(ui_function_6);
lv_image_set_src(ui_bg_12, &ui_img_bg1_png);
lv_obj_set_width( ui_bg_12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg_12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bg_12, 0 );
lv_obj_set_y( ui_bg_12, -1 );
lv_obj_set_align( ui_bg_12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg_12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg_12, LV_OBJ_FLAG_SCROLLABLE );
    lv_image_set_scale(ui_bg_12, 270);

}

void ui_function_6_screen_destroy(void)
{
   if (ui_function_6) lv_obj_del(ui_function_6);

// NULL screen variables
ui_function_6= NULL;
ui_bg_12= NULL;

}
