// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_functions_loading_page_5 = NULL;lv_obj_t *ui_bg_6 = NULL;lv_obj_t *ui_Spinner6 = NULL;lv_obj_t *ui_label_degree5 = NULL;
// event funtions

// build funtions

void ui_functions_loading_page_5_screen_init(void)
{
ui_functions_loading_page_5 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_functions_loading_page_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_functions_loading_page_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_functions_loading_page_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg_6 = lv_image_create(ui_functions_loading_page_5);
lv_image_set_src(ui_bg_6, &ui_img_1257899884);
lv_obj_set_width( ui_bg_6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg_6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bg_6, 2 );
lv_obj_set_y( ui_bg_6, 38 );
lv_obj_set_align( ui_bg_6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg_6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg_6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_bg_6, 270);

ui_Spinner6 = lv_spinner_create(ui_functions_loading_page_5);
//lv_spinner_set_anim_params(ui_Spinner6, 1000, 90);
lv_obj_set_width(ui_Spinner6, 412);
lv_obj_set_height(ui_Spinner6, 412);
lv_obj_set_align( ui_Spinner6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner6, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner6, lv_color_hex(0x1D7448), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_degree5 = lv_label_create(ui_functions_loading_page_5);
lv_obj_set_width( ui_label_degree5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label_degree5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_label_degree5, -5 );
lv_obj_set_y( ui_label_degree5, 133 );
lv_obj_set_align( ui_label_degree5, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_degree5,"function 5");
lv_obj_set_style_text_color(ui_label_degree5, lv_color_hex(0x11895B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_degree5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_degree5, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_functions_loading_page_5_screen_destroy(void)
{
   if (ui_functions_loading_page_5) lv_obj_del(ui_functions_loading_page_5);

// NULL screen variables
ui_functions_loading_page_5= NULL;
ui_bg_6= NULL;
ui_Spinner6= NULL;
ui_label_degree5= NULL;

}
