// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_FUNCTIONS_LOADING_PAGE_2_H
#define UI_FUNCTIONS_LOADING_PAGE_2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_functions_loading_page_2
extern void ui_functions_loading_page_2_screen_init(void);
extern void ui_functions_loading_page_2_screen_destroy(void);
extern lv_obj_t *ui_functions_loading_page_2;
extern lv_obj_t *ui_bg_2;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_label_degree1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

