// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_FUNCTION_6_H
#define UI_FUNCTION_6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_function_6
extern void ui_function_6_screen_init(void);
extern void ui_function_6_screen_destroy(void);
extern lv_obj_t *ui_function_6;
extern lv_obj_t *ui_bg_12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

