// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_functions_loading_page_1 = NULL;lv_obj_t *ui_bg_1 = NULL;lv_obj_t *ui_Spinner4 = NULL;lv_obj_t *ui_label_degree2 = NULL;
// event funtions

// build funtions

void ui_functions_loading_page_1_screen_init(void)
{
ui_functions_loading_page_1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_functions_loading_page_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_functions_loading_page_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_functions_loading_page_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg_1 = lv_image_create(ui_functions_loading_page_1);
lv_image_set_src(ui_bg_1, &ui_img_1257899884);
lv_obj_set_width( ui_bg_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bg_1, 7 );
lv_obj_set_y( ui_bg_1, 30 );
lv_obj_set_align( ui_bg_1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg_1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_bg_1, 270);

ui_Spinner4 = lv_spinner_create(ui_functions_loading_page_1);
//lv_spinner_set_anim_params(ui_Spinner4, 1000, 90);
lv_obj_set_width(ui_Spinner4, 412);
lv_obj_set_height(ui_Spinner4, 412);
lv_obj_set_align( ui_Spinner4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner4, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x38DECE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_degree2 = lv_label_create(ui_functions_loading_page_1);
lv_obj_set_width( ui_label_degree2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label_degree2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_label_degree2, -4 );
lv_obj_set_y( ui_label_degree2, 133 );
lv_obj_set_align( ui_label_degree2, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_degree2,"Weather");
lv_obj_set_style_text_color(ui_label_degree2, lv_color_hex(0x148CA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_degree2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_degree2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_functions_loading_page_1_screen_destroy(void)
{
   if (ui_functions_loading_page_1) lv_obj_del(ui_functions_loading_page_1);

// NULL screen variables
ui_functions_loading_page_1= NULL;
ui_bg_1= NULL;
ui_Spinner4= NULL;
ui_label_degree2= NULL;

}
