// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_FUNCTION_5_H
#define UI_FUNCTION_5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_function_5
extern void ui_function_5_screen_init(void);
extern void ui_function_5_screen_destroy(void);
extern void ui_function_5_screen_reset(void);
extern lv_obj_t *ui_function_5;
extern lv_obj_t *ui_bg_11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

