// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_GALLERY_PICTURES_H
#define UI_GALLERY_PICTURES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Gallery_pictures
extern void ui_Gallery_pictures_screen_init(void);
extern void ui_Gallery_pictures_screen_destroy(void);
extern lv_obj_t *ui_Gallery_pictures;
extern lv_obj_t *ui_bg_8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

