// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_Gallery_pictures = NULL;lv_obj_t *ui_bg_8 = NULL;
// event funtions

// build funtions

void ui_Gallery_pictures_screen_init(void)
{
ui_Gallery_pictures = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Gallery_pictures, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Gallery_pictures, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Gallery_pictures, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg_8 = lv_image_create(ui_Gallery_pictures);
lv_image_set_src(ui_bg_8, &ui_img_bg1_png);
lv_obj_set_width( ui_bg_8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg_8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bg_8, 0 );
lv_obj_set_y( ui_bg_8, -1 );
lv_obj_set_align( ui_bg_8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg_8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg_8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags\n    lv_image_set_scale(ui_bg_8, 270);

}

void ui_Gallery_pictures_screen_destroy(void)
{
   if (ui_Gallery_pictures) lv_obj_del(ui_Gallery_pictures);

// NULL screen variables
ui_Gallery_pictures= NULL;
ui_bg_8= NULL;

}
