// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_joks = NULL;lv_obj_t *ui_bg_9 = NULL;
// event funtions

// build funtions

lv_obj_t * ui_joke_label;
extern const char* get_current_joke();

void ui_joks_screen_init(void)
{
ui_joks = lv_obj_create(NULL);
lv_obj_remove_flag( ui_joks, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_joks, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_joks, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg_9 = lv_image_create(ui_joks);
lv_image_set_src(ui_bg_9, &ui_img_bg1_png);
lv_obj_set_width( ui_bg_9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg_9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bg_9, 0 );
lv_obj_set_y( ui_bg_9, -1 );
lv_obj_set_align( ui_bg_9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg_9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg_9, LV_OBJ_FLAG_SCROLLABLE );
    lv_image_set_scale(ui_bg_9, 270);
 // Slightly smaller so dots are visible

    // --- MANUALLY ADDED JOKE LABEL ---
    ui_joke_label = lv_label_create(ui_joks);
    lv_label_set_long_mode(ui_joke_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(ui_joke_label, 280); // Wrap width to fit the 412x412 screen safely
    lv_obj_set_style_text_align(ui_joke_label, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(ui_joke_label, LV_ALIGN_CENTER, 0, 0); // Put in exact center
    lv_obj_set_style_text_color(ui_joke_label, lv_color_hex(0xFFFFFF), 0); // MAKE IT WHITE!
    lv_obj_set_style_text_font(ui_joke_label, &lv_font_montserrat_20, 0);
    lv_label_set_text(ui_joke_label, "Loading joke...");
}

void ui_joks_screen_destroy(void)
{
   if (ui_joks) lv_obj_del(ui_joks);

// NULL screen variables
ui_joks= NULL;
ui_bg_9= NULL;
ui_joke_label= NULL;

}
