// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_JOKS_H
#define UI_JOKS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_joks
extern void ui_joks_screen_init(void);
extern void ui_joks_screen_destroy(void);
extern lv_obj_t *ui_joks;
extern lv_obj_t *ui_bg_9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

