// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_STARTUP_PAGE_H
#define UI_STARTUP_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_startup_page
extern void ui_startup_page_screen_init(void);
extern void ui_startup_page_screen_destroy(void);
extern void ui_event_startup_page( lv_event_t * e);
extern lv_obj_t *ui_startup_page;
extern lv_obj_t *ui_bg6;
extern lv_obj_t *ui_title_group_1;
extern lv_obj_t *ui_Spinner3;
// CUSTOM VARIABLES
extern lv_obj_t *uic_YUMOBUILDS;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

