// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *uic_YUMOBUILDS;
lv_obj_t *ui_startup_page = NULL;lv_obj_t *ui_bg6 = NULL;lv_obj_t *ui_title_group_1 = NULL;lv_obj_t *ui_Spinner3 = NULL;
// event funtions
void ui_event_startup_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      top_Animation(ui_title_group_1, 0);
}
}

// build funtions

void ui_startup_page_screen_init(void)
{
ui_startup_page = lv_obj_create(NULL);
lv_obj_remove_flag( ui_startup_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_startup_page, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_startup_page, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_startup_page, lv_color_hex(0xEAEAEA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_startup_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg6 = lv_image_create(ui_startup_page);
lv_image_set_src(ui_bg6, &ui_img_536642854);
lv_obj_set_width( ui_bg6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bg6, 3 );
lv_obj_set_y( ui_bg6, 28 );
lv_obj_set_align( ui_bg6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_bg6, 256);

ui_title_group_1 = ui_titlegroup_create(ui_startup_page);
lv_obj_set_x( ui_title_group_1, 1 );
lv_obj_set_y( ui_title_group_1, -298 );
lv_obj_set_align( ui_title_group_1, LV_ALIGN_BOTTOM_MID );

lv_obj_set_x( ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE), 4 );
lv_obj_set_y( ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE), 0 );
lv_obj_set_align( ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE), LV_ALIGN_TOP_MID );
lv_label_set_text(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE),"YUMO BUILDS ");
lv_obj_set_style_text_color(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE), lv_color_hex(0xFA8CF5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE), 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_TITLE), &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_label_set_text(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE),"Smart Cube");
lv_obj_set_style_text_color(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_comp_get_child(ui_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner3 = lv_spinner_create(ui_startup_page);
//lv_spinner_set_anim_params(ui_Spinner3, 1000, 90);
lv_obj_set_width(ui_Spinner3, 412);
lv_obj_set_height(ui_Spinner3, 412);
lv_obj_set_x( ui_Spinner3, 1 );
lv_obj_set_y( ui_Spinner3, 0 );
lv_obj_set_align( ui_Spinner3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Spinner3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Spinner3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Spinner3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0xFF40D2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_startup_page, ui_event_startup_page, LV_EVENT_ALL, NULL);
uic_YUMOBUILDS = ui_startup_page;

}

void ui_startup_page_screen_destroy(void)
{
   if (ui_startup_page) lv_obj_del(ui_startup_page);

// NULL screen variables
uic_YUMOBUILDS= NULL;
ui_startup_page= NULL;
ui_bg6= NULL;
ui_title_group_1= NULL;
ui_Spinner3= NULL;

}
