// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_weather_time = NULL;lv_obj_t *ui_bg_4 = NULL;lv_obj_t *ui_city_gruop_1 = NULL;lv_obj_t *ui_weather_title_group_3 = NULL;lv_obj_t *ui_label_degree = NULL;lv_obj_t *ui_rain_group = NULL;lv_obj_t *ui_rain_icon = NULL;lv_obj_t *ui_rain_percent = NULL;lv_obj_t *ui_wind_group = NULL;lv_obj_t *ui_wind_icon = NULL;lv_obj_t *ui_wind_speed = NULL;lv_obj_t *ui_weather_image_group = NULL;
lv_obj_t *ui_clouds_wrapper = NULL;lv_obj_t *ui_sun = NULL;lv_obj_t *ui_clouds = NULL;lv_obj_t *ui_clock1 = NULL;lv_obj_t *ui_dots1 = NULL;lv_obj_t *ui_day_night = NULL;lv_obj_t *ui_batterygroup1 = NULL;
lv_obj_t *ui_weather_rain_1 = NULL;
lv_obj_t *ui_weather_rain_2 = NULL;
lv_obj_t *ui_weather_rain_3 = NULL;
// event funtions
void ui_event_weather_time( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      left_Animation(ui_label_degree, 0);
      right_Animation(ui_sun, 100);
      right_Animation(ui_clouds, 100);
}
}

// build funtions

void ui_weather_time_screen_init(void)
{
ui_weather_time = lv_obj_create(NULL);
lv_obj_remove_flag( ui_weather_time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_weather_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_weather_time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bg_4 = lv_image_create(ui_weather_time);
lv_image_set_src(ui_bg_4, &ui_img_bg3_png);
    lv_image_set_scale(ui_bg_4, 270);
lv_obj_set_width( ui_bg_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bg_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bg_4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bg_4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_bg_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_city_gruop_1 = ui_titlegroup_create(ui_weather_time);
lv_obj_set_x( ui_city_gruop_1, -48 );
lv_obj_set_y( ui_city_gruop_1, -284 );
lv_obj_set_align( ui_city_gruop_1, LV_ALIGN_BOTTOM_MID );

lv_obj_set_x( ui_comp_get_child(ui_city_gruop_1, UI_COMP_TITLEGROUP_TITLE), -28 );
lv_obj_set_y( ui_comp_get_child(ui_city_gruop_1, UI_COMP_TITLEGROUP_TITLE), 0 );
lv_obj_set_align( ui_comp_get_child(ui_city_gruop_1, UI_COMP_TITLEGROUP_TITLE), LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_comp_get_child(ui_city_gruop_1, UI_COMP_TITLEGROUP_TITLE),"london");
lv_obj_set_style_text_font(ui_comp_get_child(ui_city_gruop_1, UI_COMP_TITLEGROUP_TITLE), &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_label_set_text(ui_comp_get_child(ui_city_gruop_1, UI_COMP_TITLEGROUP_SUBTITLE),"2/Monday/2026");

ui_weather_title_group_3 = ui_titlegroup_create(ui_weather_time);
lv_obj_set_x( ui_weather_title_group_3, -59 );
lv_obj_set_y( ui_weather_title_group_3, -112 );
lv_obj_set_align( ui_weather_title_group_3, LV_ALIGN_BOTTOM_MID );

lv_obj_set_x( ui_comp_get_child(ui_weather_title_group_3, UI_COMP_TITLEGROUP_TITLE), -3 );
lv_obj_set_y( ui_comp_get_child(ui_weather_title_group_3, UI_COMP_TITLEGROUP_TITLE), -2 );
lv_label_set_text(ui_comp_get_child(ui_weather_title_group_3, UI_COMP_TITLEGROUP_TITLE),"Partly Cloudy");

lv_label_set_text(ui_comp_get_child(ui_weather_title_group_3, UI_COMP_TITLEGROUP_SUBTITLE),"Max: 18° Min: 12°");

ui_label_degree = lv_label_create(ui_weather_time);
lv_obj_set_width( ui_label_degree, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label_degree, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_label_degree, 69 );
lv_obj_set_y( ui_label_degree, 92 );
lv_obj_set_align( ui_label_degree, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_degree,"25°");
lv_obj_set_style_text_color(ui_label_degree, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_degree, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_degree, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rain_group = lv_obj_create(ui_weather_time);
lv_obj_set_width( ui_rain_group, LV_SIZE_CONTENT);
lv_obj_set_height( ui_rain_group, LV_SIZE_CONTENT);
lv_obj_set_x( ui_rain_group, 130 );
lv_obj_set_y( ui_rain_group, -40 );
lv_obj_set_align( ui_rain_group, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_flex_flow(ui_rain_group,LV_FLEX_FLOW_ROW);
lv_obj_set_style_pad_column(ui_rain_group, 8, 0);
    lv_obj_set_flex_align(ui_rain_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_rain_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_rain_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rain_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_rain_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_rain_group, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rain_icon = lv_image_create(ui_rain_group);
lv_image_set_src(ui_rain_icon, &ui_img_rain_png);
lv_obj_set_width( ui_rain_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rain_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rain_icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rain_icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_rain_icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rain_percent = lv_label_create(ui_rain_group);
lv_obj_set_width( ui_rain_percent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rain_percent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rain_percent, LV_ALIGN_CENTER );
lv_label_set_text(ui_rain_percent,"18%");
lv_obj_set_style_text_color(ui_rain_percent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rain_percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rain_percent, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wind_group = lv_obj_create(ui_weather_time);
lv_obj_set_width( ui_wind_group, LV_SIZE_CONTENT);
lv_obj_set_height( ui_wind_group, LV_SIZE_CONTENT);
lv_obj_set_x( ui_wind_group, 220 );
lv_obj_set_y( ui_wind_group, -40 );
lv_obj_set_align( ui_wind_group, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_flex_flow(ui_wind_group,LV_FLEX_FLOW_ROW);
lv_obj_set_style_pad_column(ui_wind_group, 8, 0);
    lv_obj_set_flex_align(ui_wind_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wind_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wind_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wind_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_wind_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wind_group, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wind_icon = lv_image_create(ui_wind_group);
lv_image_set_src(ui_wind_icon, &ui_img_wind_png);
lv_obj_set_width( ui_wind_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wind_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wind_icon, -56 );
lv_obj_set_y( ui_wind_icon, -84 );
lv_obj_set_align( ui_wind_icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wind_icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_wind_icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wind_speed = lv_label_create(ui_wind_group);
lv_obj_set_width( ui_wind_speed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wind_speed, LV_SIZE_CONTENT);   /// 1
// removed offset
// removed offset
lv_obj_set_align( ui_wind_speed, LV_ALIGN_CENTER );
lv_label_set_text(ui_wind_speed,"54 km/h");
lv_obj_set_style_text_color(ui_wind_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wind_speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wind_speed, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weather_image_group = lv_obj_create(ui_weather_time);
lv_obj_set_width( ui_weather_image_group, 240);
lv_obj_set_height( ui_weather_image_group, 306);
lv_obj_set_x( ui_weather_image_group, 14 );
lv_obj_set_y( ui_weather_image_group, 0 );
lv_obj_set_align( ui_weather_image_group, LV_ALIGN_TOP_RIGHT );
lv_obj_remove_flag( ui_weather_image_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_weather_image_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_weather_image_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sun = lv_image_create(ui_weather_image_group);
lv_image_set_src(ui_sun, &ui_img_sun_png);
lv_obj_set_width( ui_sun, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sun, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_sun, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_sun, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_sun, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_clouds_wrapper = lv_obj_create(ui_weather_image_group);
lv_obj_set_width(ui_clouds_wrapper, LV_SIZE_CONTENT);
lv_obj_set_height(ui_clouds_wrapper, LV_SIZE_CONTENT);
lv_obj_set_align(ui_clouds_wrapper, LV_ALIGN_TOP_RIGHT);
lv_obj_set_x(ui_clouds_wrapper, -20); // Fixed wrapper offset
lv_obj_set_y(ui_clouds_wrapper, 20);
lv_obj_set_style_bg_opa(ui_clouds_wrapper, 0, LV_PART_MAIN);
lv_obj_set_style_border_width(ui_clouds_wrapper, 0, LV_PART_MAIN);
lv_obj_set_style_pad_all(ui_clouds_wrapper, 0, LV_PART_MAIN);
lv_obj_remove_flag(ui_clouds_wrapper, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_add_flag(ui_clouds_wrapper, LV_OBJ_FLAG_OVERFLOW_VISIBLE);

ui_clouds = lv_image_create(ui_clouds_wrapper); // Set the wrapper as the parent
lv_image_set_src(ui_clouds, &ui_img_clouds_png);
lv_obj_set_width( ui_clouds, LV_SIZE_CONTENT);
lv_obj_set_height( ui_clouds, LV_SIZE_CONTENT);
lv_obj_set_align( ui_clouds, LV_ALIGN_TOP_RIGHT );
lv_obj_set_x( ui_clouds, 0 ); // Let the animation move this internally
lv_obj_set_y( ui_clouds, 0 );
lv_obj_add_flag( ui_clouds, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_add_flag( ui_clouds, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_remove_flag( ui_clouds, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_clock1 = lv_label_create(ui_weather_time);
lv_obj_set_width( ui_clock1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock1, -87 );
lv_obj_set_y( ui_clock1, -45 );
lv_obj_set_align( ui_clock1, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock1,"3  25");
lv_obj_set_style_text_color(ui_clock1, lv_color_hex(0xFBF2F3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clock1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dots1 = lv_label_create(ui_weather_time);
lv_obj_set_width( ui_dots1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dots1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dots1, -97 );
lv_obj_set_y( ui_dots1, -46 );
lv_obj_set_align( ui_dots1, LV_ALIGN_CENTER );
lv_label_set_text(ui_dots1,":");
lv_obj_set_style_text_color(ui_dots1, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dots1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dots1, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_day_night = lv_label_create(ui_weather_time);
lv_obj_set_width( ui_day_night, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day_night, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_day_night, -6 );
lv_obj_set_y( ui_day_night, -39 );
lv_obj_set_align( ui_day_night, LV_ALIGN_CENTER );
lv_label_set_text(ui_day_night,"am");
lv_obj_set_style_text_color(ui_day_night, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_day_night, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_day_night, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batterygroup1 = ui_batterygroup_create(ui_weather_time);
lv_obj_set_x( ui_batterygroup1, -7 );
lv_obj_set_y( ui_batterygroup1, 12 );

lv_obj_add_event_cb(ui_weather_time, ui_event_weather_time, LV_EVENT_ALL, NULL);

}

void ui_weather_time_screen_destroy(void)
{
   if (ui_weather_time) lv_obj_del(ui_weather_time);

// NULL screen variables
ui_weather_time= NULL;
ui_bg_4= NULL;
ui_city_gruop_1= NULL;
ui_weather_title_group_3= NULL;
ui_label_degree= NULL;
ui_rain_group= NULL;
ui_rain_icon= NULL;
ui_rain_percent= NULL;
ui_wind_group= NULL;
ui_wind_icon= NULL;
ui_wind_speed= NULL;
ui_weather_image_group= NULL;
ui_sun= NULL;
ui_clouds= NULL;
ui_clock1= NULL;
ui_dots1= NULL;
ui_day_night= NULL;
ui_batterygroup1= NULL;

}
