// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_WEATHER_TIME_H
#define UI_WEATHER_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather_time
extern void ui_weather_time_screen_init(void);
extern void ui_weather_time_screen_destroy(void);
extern void ui_event_weather_time( lv_event_t * e);
extern lv_obj_t *ui_weather_time;
extern lv_obj_t *ui_bg_4;
extern lv_obj_t *ui_city_gruop_1;
extern lv_obj_t *ui_weather_title_group_3;
extern lv_obj_t *ui_label_degree;
extern lv_obj_t *ui_rain_group;
extern lv_obj_t *ui_rain_icon;
extern lv_obj_t *ui_rain_percent;
extern lv_obj_t *ui_wind_group;
extern lv_obj_t *ui_wind_icon;
extern lv_obj_t *ui_wind_speed;
extern lv_obj_t *ui_weather_image_group;
extern lv_obj_t *ui_sun;
extern lv_obj_t *ui_clouds;
extern lv_obj_t *ui_clock1;
extern lv_obj_t *ui_dots1;
extern lv_obj_t *ui_day_night;
extern lv_obj_t *ui_batterygroup1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

